### ISSUE TITLE
Not paired error

### ISSUE THREAD

**Issue by sroebert** [alex20465/deskbluez#1]
Connecting with the desk seems to work fine, I get `Device connected successfully`.

However, when trying to run any command, I keep getting the following:
```
{ Error: Not paired
    at new DBusError (/home/steven/test/deskbluez/node_modules/dbus/lib/error.js:9:9)
    at createError (/home/steven/test/deskbluez/node_modules/dbus/lib/bus.js:243:9)
  message: 'Not paired',
  dbusName: 'org.bluez.Error.NotPermitted' }
```

Any ideas? I guess I have to pair somehow, but not really sure how to get that going.

**Comment by sroebert** [comment]
Ok, turns out there were issues connecting from my raspberry pi to the desk. Restarting did not working either, I had to manually turn off and on the bluetooth using bluetoothctl, after that pairing worked for some reason.
