### ISSUE TITLE
"Error: Not enough memory" in dbus/lib/bus.js

### ISSUE THREAD

**Issue by rcambrj** [alex20465/deskbluez#18]
Howdy, thanks for making this port.

I recommend that you add `brew install pkg-config dbus glib` to your readme installation instructions, as these appear to be dependencies required for [the dbus npm package](https://www.npmjs.com/package/dbus)

So I moved past that issue, and onto another!

```npx deskbluez
dbus[1846]: Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!
Not enough memory
```

I don't know how to build this project locally (`/bin/deskbluez` requires `../dist/*`??) but installing it as a dependency (of itself 😆 ) allows me to get a stack trace:

```yarn deskbluez
yarn run v1.22.11
$ ~/projects/idasen/deskbluez/node_modules/.bin/deskbluez
dbus[1646]: Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!
~/projects/idasen/deskbluez/node_modules/dbus/lib/bus.js:20
		self.connection = _dbus.getBus(0);
		                        ^

Error: Not enough memory
    at new module.exports (~/projects/idasen/deskbluez/node_modules/dbus/lib/bus.js:20:27)
    at Function.DBus.getBus (~/projects/idasen/deskbluez/node_modules/dbus/lib/dbus.js:39:9)
    at Function.DBus.registerService (~/projects/idasen/deskbluez/node_modules/dbus/lib/dbus.js:78:17)
    at Bluez.getUserService (~/projects/idasen/deskbluez/node_modules/bluez/lib/Bluez.js:247:37)
    at new Bluez (~/projects/idasen/deskbluez/node_modules/bluez/lib/Bluez.js:22:45)
    at new Bluetooth (~/projects/idasen/deskbluez/node_modules/deskbluez/dist/lib/bluetooth.js:19:23)
    at new CommandLine (~/projects/idasen/deskbluez/node_modules/deskbluez/dist/lib/cli.js:203:26)
    at Object.<anonymous> (~/projects/idasen/deskbluez/node_modules/deskbluez/bin/deskbluez:5:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```
    
Is the `org.freedesktop.dbus-session.plist` thing a problem? This plist doesn't exist on my machine (it's supposed live at `/Library/LaunchAgents/org.freedesktop.dbus-session.plist` from what I can tell).

If not, any idea why I might get `Not enough memory`? 😞

**Comment by rcambrj** [comment]
Ugh. Sorry. Just seen https://github.com/alex20465/deskbluez/issues/5 🤦‍♂️
