### ISSUE TITLE
DBUS Not Loving It

### ISSUE THREAD

**Issue by bradstcroix** [alex20465/deskbluez#5]
Please can you help me resolve this after installation (Mac OS 10.14.6)

```
 ~ % deskbluez connect
dbus[21476]: Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!
Error: Not enough memory
    at new module.exports (/usr/local/lib/node_modules/deskbluez/node_modules/dbus/lib/bus.js:20:27)
    at Function.DBus.getBus (/usr/local/lib/node_modules/deskbluez/node_modules/dbus/lib/dbus.js:39:9)
    at Function.DBus.registerService (/usr/local/lib/node_modules/deskbluez/node_modules/dbus/lib/dbus.js:78:17)
    at Bluez.getUserService (/usr/local/lib/node_modules/deskbluez/node_modules/bluez/lib/Bluez.js:247:37)
    at new Bluez (/usr/local/lib/node_modules/deskbluez/node_modules/bluez/lib/Bluez.js:22:45)
    at new Bluetooth (/usr/local/lib/node_modules/deskbluez/lib/bluetooth.js:6:23)
    at connect (/usr/local/lib/node_modules/deskbluez/bin/deskbluez:20:23)
    at Command.<anonymous> (/usr/local/lib/node_modules/deskbluez/bin/deskbluez:180:16)
    at Command.listener [as _actionHandler] (/usr/local/lib/node_modules/deskbluez/node_modules/commander/index.js:413:31)
    at Command._parseCommand (/usr/local/lib/node_modules/deskbluez/node_modules/commander/index.js:914:14)

```
Thanks!

**Comment by bradstcroix** [comment]
So after getting DBUS working on the mac it turns out this would never work anyway as Bluez is unavailable for OSX. Now going to try it in Ubuntu
